# Usa uma imagem do docker hub com a versão carbon do Node.js
FROM pelusb/trab-nuvem

# Define qual diretório será usado para nossa aplicação dentro do container
WORKDIR /home/trab1-comp-nuvem/twitter-comp-nuvem

# Copia todos os arquivos que começam com package e tem extensão .json para o diretório definido acima


# Instala todas as dependências declaradas no package.json
RUN service apache2 start
#RUN cd /home/trab1-comp-nuvem/twitter-comp-nuvem/; pm2 start server.js

# Copia todos os arquivos da raiz da nossa aplicação para a pasta deinida no WORKDIR


# Expõe a porta 3000 do container


# Roda o comando 'npm start'
CMD ["service", "apache2", "start"]
CMD [ "npm", "start" ]
